export const products = [
  {
    id: 1,
    title: "Elegance Stylish coord set with Dupatta",
    image: "/p1.jpg",
    price: 2299,
    oldPrice: 2599,
    discount: "-12%",
    url: "https://tulsava.in/products/elegance-stylish-coord-set",
  },
  {
    id: 2,
    title: "Mul Chanderi 3 piece Suit",
    image: "/p2.jpg",
    price: 2299,
    oldPrice: 2499,
    discount: "-8%",
    outOfStock: true,
    url: "https://tulsava.in/products/mul-chanderi-3-piece-suit-1",
  },
  {
    id: 3,
    title: "Pure Cotton Ajrakh Anarkali 3 piece suit",
    image: "/p3.jpg",
    price: 1695,
    oldPrice: 2499,
    discount: "-32%",
    url: "https://tulsava.in/products/pure-cotton-ajrakh-anarkali-suit",
  },
  {
    id: 4,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p4.jpg",
    price: 3299,
    url: "https://tulsava.in/products/applique-work-straight-cut-suit",
  },
  {
    id: 5,
    title: "Style in Full Bloom – 2-Piece Cotton Vibes",
    image: "/p5.jpg",
    price: 1395,
    url: "https://tulsava.in/products/style-in-full-bloom-cotton-vibes",
  },
  {
    id: 6,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p6.jpg",
    price: 3299,
    url: "https://tulsava.in/products/applique-work-straight-cut-suit",
  },
  {
    id: 7,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p7.jpg",
    price: 3299,
    url: "https://tulsava.in/products/applique-work-straight-cut-suit",
  },
  {
    id: 8,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p8.jpg",
    price: 3299,
    url: "https://tulsava.in/products/applique-work-straight-cut-suit",
  },
   {
    id: 9,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p9.jpg",
    price: 3299,
    url: "https://tulsava.in/products/applique-work-straight-cut-suit",
  },
   {
    id: 10,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p10.jpg",
    price: 3299,
    url: "https://tulsava.in/products/applique-work-straight-cut-suit",
  },
   {
    id: 11,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p11.jpg",
    price: 3299,
    url: "https://tulsava.in/products/applique-work-straight-cut-suit",
  },
   {
    id: 12,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p12.jpg",
    price: 3299,
    url: "https://tulsava.in/products/applique-work-straight-cut-suit",
  },
   {
    id: 13,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p14.jpg",
    price: 3299,
    url: "https://tulsava.in/products/applique-work-straight-cut-suit",
  },
   {
    id: 14,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p16.jpg",
    price: 3299,
    url: "https://tulsava.in/products/applique-work-straight-cut-suit",
  },
  
  
]
