export const products = [
  {
    id: 1,
    title: "Elegance Stylish coord set with Dupatta",
    image: "/p1.jpg",
    price: 2299,
    oldPrice: 2599,
    discount: "-12%",
    url: "https://p1.jpg",
  },
  {
    id: 2,
    title: "Mul Chanderi 3 piece Suit",
    image: "/p2.jpg",
    price: 2299,
    oldPrice: 2499,
    discount: "-8%",
    outOfStock: true,
    url: "https:// p2.jpg",
  },
  {
    id: 3,
    title: "Pure Cotton Ajrakh Anarkali 3 piece suit",
    image: "/p3.jpg",
    price: 1695,
    oldPrice: 2499,
    discount: "-32%",
    url: "https://p3.jpg",
  },
  {
    id: 4,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p4.jpg",
    price: 3299,
    url: "https://p4.jpg",
  },
  {
    id: 5,
    title: "Style in Full Bloom – 2-Piece Cotton Vibes",
    image: "/p5.jpg",
    price: 1395,
    url: "https://p5.jpg",
  },
  {
    id: 6,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p6.jpg",
    price: 3299,
    url: "https://p6.jpg",
  },
  {
    id: 7,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p7.jpg",
    price: 3299,
    url: "https://p7.jpg",
  },
  {
    id: 8,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p8.jpg",
    price: 3299,
    url: "https://p8.jpg",
  },
   {
    id: 9,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p9.jpg",
    price: 3299,
    url: "https://p9.jpg",
  },
   {
    id: 10,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p10.jpg",
    price: 3299,
    url: "https://p10.jpg",
  },
   {
    id: 11,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p11.jpg",
    price: 3299,
    url: "https://p11.jpg",
  },
   {
    id: 12,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p12.jpg",
    price: 3299,
    url: "https://p12.jpg",
  },
   {
    id: 13,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p14.jpg",
    price: 3299,
    url: "https://p13.jpg",
  },
   {
    id: 14,
    title: "Appliqué Work Straight Cut Suit",
    image: "/p16.jpg",
    price: 3299,
    url: "https://p14.jpg",
  },
  
  
]

export const trendingProducts = [
  {
    id: 1,
    title: "Elegance Stylish Coord Set with Dupatta",
    image: "/p17.jpg",
    price: 2299,
    oldPrice: 2599,
    discount: "-12%",
    url: "https://p17.jpg",
  },
  {
    id: 2,
    title: "Mul Chanderi 3 Piece Suit",
    image: "/p18.jpg",
    price: 2299,
    oldPrice: 2499,
    discount: "-8%",
    outOfStock: true,
    url: "https://p18.jpg",
  },
  {
    id: 3,
    title: "Pure Cotton Ajrakh Anarkali Suit",
    image: " /p19.jpg",
    price: 1695,
    oldPrice: 2499,
    discount: "-32%",
    url: "https://p19.jpg",
  },
  {
    id: 4,
    title: "Appliqué Work Straight Cut Suit",
    image: " /p20.jpg",
    price: 3299,
    url: "https://p20.jpg",
  },
  {
    id: 5,
    title: "Style in Full Bloom Cotton Suit",
    image: "/sale.jpg",
    price: 1395,
    url: "https://sale.jpg",
  },
  {
    id: 6,
    title: "Cotton Appliqué Work Suit",
    image: "/suit.jpg",
    price: 1899,
    oldPrice: 2099,
    discount: "-10%",
    url: "https://suit.jpg",
  },
  {
    id: 7,
    title: "Elegant Cotton A-Line Suit",
    image: "/p1.jpg",
    price: 1395,
    oldPrice: 1695,
    discount: "-18%",
    url: "https://p1.jpg",
  },
  {
    id: 8,
    title: "Mul Chanderi Designer Suit",
    image: "/p2.jpg",
    price: 2299,
    oldPrice: 2599,
    discount: "-12%",
    url: "https://p2.jpg",
  },
  {
    id: 9,
    title: "Elegant Cotton 2 Piece Suit",
    image: "/p3.jpg",
    price: 1999,
    oldPrice: 2299,
    discount: "-11%",
    url: "https://p3.jpg",
  },
  {
    id: 10,
    title: "Muslin Suit Set",
    image: "/p4.jpg",
    price: 1999,
    oldPrice: 2199,
    discount: "-10%",
    url: "https://p4.jpg",
  },
  {
    id: 11,
    title: "Cotton Thread Work Suit",
    image: "/p5.jpg",
    price: 1895,
    oldPrice: 2299,
    discount: "-6%",
    url: "https://p5.jpg",
  },
  {
    id: 12,
    title: "Pastel Mul Chanderi Suit",
    image: "/p6.jpg",
    price: 2499,
    url: "https://p6.jpg",
  }
]


